language: rust
sudo: false
cache:
- apt
- cargo
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
notifications:
  slack:
    rooms:
      secure: Bwlor4yN9N0yNSC2c1e6tR93ZMYkf1340/T7kAKsKIUGhxaXIcmLfXL5AGMrYCo3zZy+fQ86sEOImveipIYRU9jcFZXtCfWPX3aad1Cw5NrfxNHrSyU37j23boGec8yqv4pmhgS5ELlPtP7IjMkaE2NBIQOzhKU5kmLjTwL0eh0U5+bmw8Y9DIVMIz5ql1QW3x5qd1YFbcnrFDd+k6I4a+OVxO46HZKMV/mbvnj/FpsQYAf4U1Mb2ypugL1uOszNj5Cu6wt/qMsKJVMm7HcYKmYFsjzws7zAAWW5h0vlRLoIz6Duur8AobxuWiJFb0LfPzYE2xZYsYt52nvCfX5OJJEyDzjAXdDbDPHzANUumuvjTpYWfSTbGHFUjjNpjylPMcYzXtfxMPj474deV9veMWYYOOUpjcYVRzH6AU1bEPzSmXGcbCeRM7PfANyRLZ5X0EK8draX8M69rcaswUdUCfLB9wCuLZE6G2m1qpNr9CinaT0oOKBeJleizhlJXam4jbTxdOmAq6F+P7OaOHEY8lbUyPjLhVhgOMXuGUZiYaqiUzl2Yc0BvjJ0nlXo3BsazVBA+OlQeeiWMz4GFJxWWacudRQfLJbQ8uHcVv0wNXHOliAb0LJJDVq7j+AgQq3xedchL1nXAfHA05VI1xP5JDb1/KQLykqDw/u0XtVOE1U=
