# -*- mode:toml; coding:utf-8-unix; -*-
# ==============================================================================
[package]
name            = "sif"
version         = "0.1.0"
authors         = ["hanepjiv <hanepjiv@gmail.com>"]
license         = "MIT/Apache-2.0"
# ==============================================================================
[dependencies]
ffi             = "^0.0.2"
gl              = "^0.6.1"
image           = "^0.10.1"
libc            = "^0.2.13"
log             = "^0.3.6"
num             = "^0.1.32"
uuid            = { version = "^0.2.2", features = ["v4"] }
