# -*- mode:toml; coding:utf-8-unix; -*-
# =============================================================================
[workspace]
members                         = [
                                "sif",
                                "sif_error",
                                "sif_graphics",
                                "sif_manager",
                                "sif_math",
                                "sif_nursery",
                                "sif_renderer",
                                "sif_three",
                                ]
# =============================================================================
[replace]
#"sif_error:0.1.0"               = { path="./sif_error" }
#"sif_graphics:0.1.0"            = { path="./sif_graphics" }
#"sif_manager:0.1.0"             = { path="./sif_manager" }
#"sif_math:0.1.0"                = { path="./sif_math" }
#"sif_nursery:0.1.0"             = { path="./sif_nursery" }
#"sif_renderer:0.1.0"            = { path="./sif_renderer" }
#"sif_three:0.1.0"               = { path="./sif_three" }
