# -*- mode:toml; coding:utf-8-unix; -*-
# =============================================================================
[package]
name            = "sif"
version         = "0.3.0"
authors         = ["hanepjiv <hanepjiv@gmail.com>"]
license         = "MIT/Apache-2.0"
keywords        = ["subsystem", "game", "math", "graphics"]
description     = "Game libraries"
readme          = "README.md"
documentation   = "https://github.com/hanepjiv/sif-rs/wiki"
homepage        = "https://github.com/hanepjiv/sif-rs"
repository      = "https://github.com/hanepjiv/sif-rs.git"
publish         = false
# =============================================================================
[dependencies]
gl              = { default-features = false, version = "^0.10" }
log             = { default-features = false, version = "^0.4" }
num             = { default-features = false, version = "^0.1" }
# -----------------------------------------------------------------------------
[dependencies.image]
#default-features = false
version = "^0.19"
features = ["png_codec"]
