# -*- mode:toml; coding:utf-8-unix; -*-
# =============================================================================
[package]
name            = "sif"
version         = "0.1.5"
authors         = ["hanepjiv <hanepjiv@gmail.com>"]
license         = "MIT/Apache-2.0"
keywords        = ["subsystem", "game", "math", "graphics"]
description     = "Game libraries"
readme          = "README.md"
documentation   = "https://github.com/hanepjiv/sif-rs/wiki"
homepage        = "https://github.com/hanepjiv/sif-rs"
repository      = "https://github.com/hanepjiv/sif-rs.git"
# =============================================================================
[dependencies]
ffi             = "^0.0.2"
gl              = "^0.6.1"
image           = "^0.10.3"
libc            = "^0.2.17"
num             = "^0.1.36"
uuid            = { version = "^0.3.1", features = ["v4"] }
